title: "East Lansing Kart Track"
description: "Real Racing for the Whole Family"
baseurl: ""  # leave empty if running from the root URL
url: "https://corypahl.github.io/karttrack"  # update as appropriate
